# Generated by Django 3.2 on 2021-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpn', models.CharField(help_text='Enter 12 digit bel part number. If unknown use 999999999999', max_length=12, unique=True)),
            ],
        ),
    ]
