# Generated by Django 3.2 on 2021-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matmgmt', '0002_rename_bpn_belpartnumber_belpartno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belpartnumber',
            name='belPartNo',
            field=models.CharField(help_text='Enter 12 digit bel part number. If unknown use 999999999999', max_length=12, unique=True, verbose_name='BEL PART NUMBER'),
        ),
    ]
