# Generated by Django 3.2 on 2021-04-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matmgmt', '0003_alter_belpartnumber_belpartno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(help_text='select mpn or add new', max_length=30, verbose_name='MPN - Manufacturer Part Num')),
                ('description', models.CharField(help_text='select part description or add new', max_length=50)),
                ('belPartNo', models.ForeignKey(help_text='Select bel part number or add new', on_delete=django.db.models.deletion.RESTRICT, to='matmgmt.belpartnumber')),
            ],
        ),
    ]
