# Generated by Django 3.2 on 2021-04-25 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matmgmt', '0005_partmaster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(help_text='Enter the qty')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('modifiedDate', models.DateField(auto_now=True)),
                ('comment', models.CharField(blank=True, help_text='Add an optional remarks here for reference', max_length=30)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('partMaster', models.ForeignKey(help_text='select the partnumber or add new', on_delete=django.db.models.deletion.RESTRICT, to='matmgmt.partmaster')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_loc', models.CharField(help_text='Enter cupboard or drawer name', max_length=25)),
                ('secondary_loc', models.CharField(help_text='Enter slot/pack Number', max_length=25)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservedQty', models.PositiveIntegerField()),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('modifiedDate', models.DateField(auto_now=True)),
                ('comment', models.CharField(blank=True, help_text='Add an optional remark for what it is reserved for easy reference', max_length=30)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='matmgmt.inventory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='storeLoc',
            field=models.ForeignKey(help_text='select or add a storage location for the inventary', on_delete=django.db.models.deletion.RESTRICT, to='matmgmt.storelocation'),
        ),
    ]
