# Generated by Django 3.2 on 2021-04-25 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matmgmt', '0006_auto_20210425_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, help_text='Add an optional remark for where it is used for easy reference', max_length=30)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
