# Generated by Django 3.2 on 2021-04-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matmgmt', '0007_stockissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelocation',
            name='secondary_loc',
        ),
        migrations.AddField(
            model_name='inventory',
            name='secondary_loc',
            field=models.CharField(default='default', help_text='Enter slot/pack Number', max_length=25),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='primary_loc',
            field=models.CharField(help_text='Enter cupboard or drawer number', max_length=25),
        ),
    ]
