# Generated by Django 3.2 on 2021-05-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matmgmt', '0012_auto_20210511_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='comment',
            field=models.CharField(blank=True, help_text='Add an optional remarks here for reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='free_stock',
            field=models.BooleanField(default=False, verbose_name='Free Stock'),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='mpn',
            field=models.CharField(help_text='select mpn or add new', max_length=30),
        ),
    ]
