# Generated by Django 3.2 on 2021-05-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matmgmt', '0013_auto_20210512_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='comment',
            field=models.CharField(help_text='Add an optional remarks here for reference', max_length=100),
        ),
    ]
