# Generated by Django 3.2 on 2021-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matmgmt', '0014_alter_inventory_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.CharField(help_text='Add an optional remark for what it is reserved for easy reference', max_length=100),
        ),
    ]
