# Generated by Django 3.2 on 2021-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matmgmt', '0015_alter_reservation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockissue',
            name='comment',
            field=models.CharField(help_text='Add an optional remark for where it is used for easy reference', max_length=100),
        ),
    ]
